Improve xxhsum output message quality
- xxhsum now prints more professional-looking error messages:
Before:
    Pb opening foo
After:
    Error: Could not open 'foo': No such file or directory.

- xxhsum will now attempt to display the architecture and the compiler
  version in the benchmark WELCOME_MESSAGE.
  It detects the following compilers:
    - Clang
    - GCC
    - Intel Compiler
    - MSVC
    - tcc
  and it should detect the following architectures:
    - x86 (+SSE2/AVX/AVX2)
    - x86_64 (+SSE2/AVX/AVX2)
    - ARM (+NEON)
    - aarch64
    - PowerPC 64
    - PowerPC
    - AVR
    - MIPS 64
    - MIPS
Before:
    ./xxhsum 0.7.0 (64-bits little endian), by Yann Collet
After:
    ./xxhsum 0.7.0 (64-bits x86_64 + SSE2 little endian), GCC 8.3.0, by Yann Collet

- Sanity checks are consistent now and give better warning messages:
Before:
    ERROR : Test  1 : 0x12345678 <> 0x02CC5D05   !!!!!

    ERROR : Test  1 : 64-bit values non equals   !!!!!
     0x1234567890ABCDEFULL != 0xEF46DB3751D8E999ULL
After:
    Error: 32-bit hash test 1: Internal sanity check failed!
    Got 0x12345678, expected 0x02CC5D05.
    Note: If you modified the hash functions, make sure to either update the values
    or temporarily comment out the tests in BMK_sanityCheck.

...and the 64-bit and 128-bit messages now match. I eventually want to name the
tests instead of just using the test number, but this is still better than before.

- xxhsum now displays "stdin" instead of "-" when reading from stdin.