remove tipi build temporary
/usr/local/share/.tipi/w/cli-281f677/xsum_sanity_check.c:31:10: error: '../xxhash.h' file not found, did you mean 'xxhash.h'?
10081
10082
         ^~~~~~~~~~~~~
10083
         "xxhash.h"
10084
1 error generated.

Since there are always some tipi build issues, remove them temporary
until it could be resolved.

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>