Add C2x version checking for "gcc-11 -pedantic"
"gcc-11 -std=c90 -pedantic" reports the following warning as an error.

```
$ CC=gcc-11 make clean all

gcc-11 -std=c90 -pedantic -Wno-long-long -Werror -Wall -Wextra -Wconversion -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wstrict-overflow=2 -c -o xxhash.o xxhash.c

In file included from xxhash.c:43:
xxhash.h: In function ‘XXH32_finalize’:
xxhash.h:557:32: error: ISO C does not support ‘[[]]’ attributes before C2X [-Werror=pedantic]
557 | # define XXH_FALLTHROUGH [[fallthrough]]
```

Since we can't use "[[...]]" style attributes with pre-C2X, we must check __STDC_VERSION__.