Fix C++ style comment
gcc-4.8 -pedantic reports the following warning (as an error).

gcc-4.8 -O3 -Wall -Wextra -Wconversion -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wstrict-overflow=2  -Werror -pedantic -Wno-long-long   -DXXH_NO_XXH3 xxhash.c -c
In file included from xxhash.c:43:0:
xxhash.h:3860:9: error: C++ style comments are not allowed in ISO C90 [-Werror]
         // MSVC 32bit mode does not support _mm_set_epi64x before 2015
         ^